[2022-01-12 22:59:28,554] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: my_dag.accurate manual__2022-01-12T22:59:24.639023+00:00 [queued]>
[2022-01-12 22:59:28,573] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: my_dag.accurate manual__2022-01-12T22:59:24.639023+00:00 [queued]>
[2022-01-12 22:59:28,573] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-12 22:59:28,573] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-12 22:59:28,574] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-12 22:59:28,590] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): accurate> on 2022-01-12 22:59:24.639023+00:00
[2022-01-12 22:59:28,597] {standard_task_runner.py:52} INFO - Started process 2659 to run task
[2022-01-12 22:59:28,598] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'accurate', 'manual__2022-01-12T22:59:24.639023+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpg9rhgwbw', '--error-file', '/tmp/tmpg95bblbn']
[2022-01-12 22:59:28,599] {standard_task_runner.py:77} INFO - Job 18: Subtask accurate
[2022-01-12 22:59:28,680] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.accurate manual__2022-01-12T22:59:24.639023+00:00 [running]> on host 5ffba7c75690
[2022-01-12 22:59:28,764] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=accurate
AIRFLOW_CTX_EXECUTION_DATE=2022-01-12T22:59:24.639023+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-12T22:59:24.639023+00:00
[2022-01-12 22:59:28,765] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-12 22:59:28,766] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'accurate'"]
[2022-01-12 22:59:28,777] {subprocess.py:85} INFO - Output:
[2022-01-12 22:59:28,780] {subprocess.py:89} INFO - accurate
[2022-01-12 22:59:28,780] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-12 22:59:28,814] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=accurate, execution_date=20220112T225924, start_date=20220112T225928, end_date=20220112T225928
[2022-01-12 22:59:28,852] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-12 22:59:28,908] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
